
let all_tests = [
    ...tests_NumberField,
    ...tests_CharField,
    ...tests_PasswordField,
    ...tests_TelField,
    ...tests_EmailField,
    ...tests_UrlField,
    ...tests_TextField,
    ...tests_SelectField,
    ...tests_CheckboxField,
    ...tests_RadioField,
    ...tests_DateField,
    ...tests_TimeField,
    ...tests_RangeField,
    ...tests_ColorField,
    ...tests_FileField,
    ...tests_JSONField,
    ...tests_Form,
];
